### PR TITLE
Validate hotkeys using string.IsNullOrEmpty

### PR DESCRIPTION
**Pull request by Ant1m3ta**

### CODE REVIEW

**Review by sampaiodias — APPROVED** [review]

**Comment by Ant1m3ta** [comment]
Chaotic clicking after I've noticed that pull request goes into master branch

**Comment by sampaiodias** [comment]
Could you elaborate more on what's happening?

**Comment by Ant1m3ta** [comment]
Sorry for this mess. I've wanted to pull changes of how hotkey string is compared.
Instead of creating proper pull request towards feat branch, I've created pull towards master. Trying to fix this mistake wanted to create new pull request. But after deleting current I've noticed that you can change target branch. So I did it.
Latest deletion of branch was purely accidental. I've create local branch for using single hotkey for opening and closing window, but gave it a bad name. I though it was already pushed, so I've rushed on github and deleted what I though was this new branch, without reading through it name. Well, it wasn't. It was the hotkey-string-check branch.

And now I'm sitting here, questioning my life decisions.

**Comment by Ant1m3ta** [comment]
@sampaiodias  Should I recover branch and reopen pull request?

**Comment by sampaiodias** [comment]
No need to worry, as this is a pretty small change I'll take a look at it myself. Thanks for the pull request, the first of CLIU :D

**Comment by sampaiodias** [comment]
@Ant1m3ta just to confirm, did you find any errors on your implementation? Tested it and worked perfectly here, I'm ready to commit the changes

**Comment by Ant1m3ta** [comment]
No errors. Working properly.

**Pull request closed without merging**
